// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toialiaqnslhsimxdtzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvaWFsaWFxbnNsaHNpbXhkdHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NjYxNjksImV4cCI6MjA1MjA0MjE2OX0._exsdZNdTfiqw9e3cBX5LqB1w5enGFHcZuoQFW6sIbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);